In [1]:
import sys
sys.path.append('/home/elilouis/sublimationofsnow/')
import sosutils

import numpy as np
import xarray as xr


In [2]:
file_list = []
for date in ['20221215', '20221216', '20221217', '20221218']:
    print(f"Downloading {date}")
    for hour in range(0,24):
        file = sosutils.download_sos_highrate_data_hour(
            date = date,
            hour = "{:02d}".format(hour),
            local_download_dir='/data2/elilouis/sublimationofsnow/hr_noqc_geo/',
            cache=True
        )
        file_list.append(file)

Caching...skipping download for 20221215, 00
Caching...skipping download for 20221215, 01
Caching...skipping download for 20221215, 02
Caching...skipping download for 20221215, 03
Caching...skipping download for 20221215, 04
Caching...skipping download for 20221215, 05
Caching...skipping download for 20221215, 06
Caching...skipping download for 20221215, 07
Caching...skipping download for 20221215, 08
Caching...skipping download for 20221215, 09
Caching...skipping download for 20221215, 10
Caching...skipping download for 20221215, 11
Caching...skipping download for 20221215, 12
Caching...skipping download for 20221215, 13
Caching...skipping download for 20221215, 14
Caching...skipping download for 20221215, 15
Caching...skipping download for 20221215, 16
Caching...skipping download for 20221215, 17
Caching...skipping download for 20221215, 18
Caching...skipping download for 20221215, 19
Caching...skipping download for 20221215, 20
Caching...skipping download for 20221215, 21
Caching...

In [3]:
len(file_list), file_list

(96,
 ['/data2/elilouis/sublimationofsnow/hr_noqc_geo/isfs_geo_hr_20221215_00.nc',
  '/data2/elilouis/sublimationofsnow/hr_noqc_geo/isfs_geo_hr_20221215_01.nc',
  '/data2/elilouis/sublimationofsnow/hr_noqc_geo/isfs_geo_hr_20221215_02.nc',
  '/data2/elilouis/sublimationofsnow/hr_noqc_geo/isfs_geo_hr_20221215_03.nc',
  '/data2/elilouis/sublimationofsnow/hr_noqc_geo/isfs_geo_hr_20221215_04.nc',
  '/data2/elilouis/sublimationofsnow/hr_noqc_geo/isfs_geo_hr_20221215_05.nc',
  '/data2/elilouis/sublimationofsnow/hr_noqc_geo/isfs_geo_hr_20221215_06.nc',
  '/data2/elilouis/sublimationofsnow/hr_noqc_geo/isfs_geo_hr_20221215_07.nc',
  '/data2/elilouis/sublimationofsnow/hr_noqc_geo/isfs_geo_hr_20221215_08.nc',
  '/data2/elilouis/sublimationofsnow/hr_noqc_geo/isfs_geo_hr_20221215_09.nc',
  '/data2/elilouis/sublimationofsnow/hr_noqc_geo/isfs_geo_hr_20221215_10.nc',
  '/data2/elilouis/sublimationofsnow/hr_noqc_geo/isfs_geo_hr_20221215_11.nc',
  '/data2/elilouis/sublimationofsnow/hr_noqc_geo/isfs_geo_h

In [8]:
ds = xr.open_mfdataset(file_list)

In [9]:
ds.time.max(), ds.time.min()

(<xarray.DataArray 'time' ()>
 array('2022-12-18T00:59:59.500000000', dtype='datetime64[ns]'),
 <xarray.DataArray 'time' ()>
 array('2022-12-15T00:00:00.500000000', dtype='datetime64[ns]'))

In [10]:
(a,b,c), (tilt, tiltaz), W_f = sosutils.calculate_planar_fit(
    ds['u_1m_c'].values.flatten(),
    ds['v_1m_c'].values.flatten(),
    ds['w_1m_c'].values.flatten()
)

In [11]:
(a,b,c), (np.rad2deg(tilt), np.rad2deg(tiltaz)), W_f

((-0.16449936, -0.0042593647, -0.00954419),
 (0.5988047583559358, 65.94983),
 array([0.00425913, 0.00954367, 0.99994539]))

In [13]:
u, v, w = sosutils.apply_planar_fit(
    ds['u_1m_c'].values.flatten(),
    ds['v_1m_c'].values.flatten(),
    ds['w_1m_c'].values.flatten(),
    a,
    W_f
)

In [17]:
ds['u_1m_c'].values.flatten(),

(array([2.150078  , 2.0361125 , 2.1026888 , ..., 0.6656874 , 0.6662806 ,
        0.66701555], dtype=float32),)

In [14]:
u,v,w

(array([2.15022774, 2.03552588, 2.10176776, ..., 0.66485326, 0.66567801,
        0.66610913]),
 array([-2.28029025, -2.43697136, -2.51520623, ..., -0.53630584,
        -0.63388841, -0.57242794]),
 array([-0.0305646 ,  0.14207847,  0.22072516, ...,  0.19725989,
         0.14290485,  0.21423814]))